---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frnotenddeployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontendpod
      labels: 
        app: frontend
    spec:
      containers:
      - name: frontendContainer
        images: rajiv84iya/jobify-frontend
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
...