---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpafrontend
  namespace: jobifyns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontenddeployment
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
...