---
apiVersion: hpa/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpafrontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frnotenddeployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
...