---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: jobifyns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backenddeployment
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
...  