---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc
  namespace: jobifyns
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002
...